# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Yaesol Kim
tagline:          'CV'
description:      'PhD Candidate in CS'
url:              http://yaesol.github.io
baseurl:          /

author:
  name:           'Yaesol'
  url:            ""

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/yaesolkim/
